### ISSUE TITLE
Renovate Bot not working in latest release (Invalid Node version)

### ISSUE THREAD

**Issue by fvidesf** [swissgrc/docker-azure-pipelines-renovate#830]
I've been using this tool for the last couple of days and it has been a blast so far!
Today I noticed my pipeline started failing , indicating the following error.
![image](https://github.com/user-attachments/assets/db7c66bb-20ab-44a4-a7f9-c0e6a5f16dcc)

I had to switch to version to the tag 37.440.0 and my pipeline started working again. Any chance it might be related to latest release that was done today?

**Comment by pascalberger** [comment]
@fvidesf This should be fixed in 38.5.0
